In [266]:
import numpy as np

In [267]:
my_list = [[1,2,3],[2,3,4],[6,7,8]]

In [268]:
arr = np.array(my_list)
print(my_list)
print(arr)
arr.min()
arr.max()


[[1, 2, 3], [2, 3, 4], [6, 7, 8]]
[[1 2 3]
 [2 3 4]
 [6 7 8]]


8

In [269]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [270]:
np.zeros((2,2))
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [271]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [272]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [273]:
np.random.randn(5)

array([ 1.16276871, -0.28436067, -0.58915586, -0.25469025, -0.9890339 ])

In [274]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [275]:
arr[8:10]

array([8, 9])

In [276]:
a = arr.copy()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [277]:
arr = np.arange(0,11)

In [278]:
arr = arr + arr
arr
arr = arr * 5
print(arr)
arr = arr * arr
print(arr)

[  0  10  20  30  40  50  60  70  80  90 100]
[    0   100   400   900  1600  2500  3600  4900  6400  8100 10000]


In [279]:
print(arr - 1000)

[-1000  -900  -600  -100   600  1500  2600  3900  5400  7100  9000]
